### PR TITLE
Fix escrow release validation

### LINKED ISSUE #283: Problem with SteemConnect Escrow Release: Escrow Issuer Can not Release Escrowed Amount
SteemConnect recently updated its escrow hot signing functionalities. Everything works fine except escrow release feature for escrow initiator. Agent and beneficiary both can release the escrow but escrow initiator can not.

I tried to release another test escrow transaction as initiator using [Steem JS](https://github.com/steemit/steem-js/) and it can be done. Here is [proof](https://steemd.com/tx/d6799255b2e40768b4661d0b01e24653dd99cb89). Please notice that `from` and `who` are the same account.

## Expected Behavior

Like escrow agent (`agent`) and beneficiary (`to`), escrow initiator (`from`) should also be able to release escrowed amount.

## Actual Behavior

Escrow transfer, escrow approval, escrow dispute works for agent, beneficiary, and initiator. But escrow release only works for agent and beneficiary.

**Here are some related links:**

Test escrow transaction: [Steemd.com](https://steemd.com/tx/f4ec78c8a109b8f9f76d85379a2073e844f39a8c)
Beneficiary approval: [Steemd.com](https://steemd.com/tx/45f16c17fa26461e33d65933c1100925dbc2068a)
Agent approval: [Steemd.com](https://steemd.com/tx/15286b3f2cb1f2644468d72a528805b60c77a8b6)

**Escrow release links:**

Beneficiary: [SteemConnect](https://steemconnect.com/sign/escrow-release?from=codebull&to=rrhasnat&agent=ifte&who=rrhasnat&receiver=codebull&escrow_id=99339411&sbd_amount=0.001%20SBD&steem_amount=0.000%20STEEM)
Agent: [SteemConnect](https://steemconnect.com/sign/escrow-release?from=codebull&to=rrhasnat&agent=ifte&who=ifte&receiver=codebull&escrow_id=99339411&sbd_amount=0.001%20SBD&steem_amount=0.000%20STEEM)
Initiator: [SteemConnect](https://steemconnect.com/sign/escrow-release?from=codebull&to=rrhasnat&agent=ifte&who=codebull&receiver=rrhasnat&escrow_id=99339411&sbd_amount=0.001%20SBD&steem_amount=0.000%20STEEM)

steemconnect-error

### PR DESCRIPTION
**Pull request by gregory-latinier**
Fixes #283

### CODE REVIEW

File: src/components/Form/CreateApp.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ class Internal extends React.Component {
         >
           {getFieldDecorator('username', {
             validateFirst: true,
+            validateTrigger: 'onBlur',
```
Comment (bonustrack) [inline src/components/Form/CreateApp.js]: This is not supposed to be here but should be fine when you merge #287
