### PR TITLE
Fix account creation

### LINKED ISSUE #345: Fix account creation
Account creation with delegation is not working anymore.

### PR DESCRIPTION
**Pull request by bonustrack**
Fix #345

### CODE REVIEW

File: src/components/Accounts/CreateAccount.js [hunk 1]
```diff
@@ -74,18 +87,22 @@ class CreateAccount extends Component {
     return (
       <div className="Sign">
         <div className="Sign__content container text-left my-2 Sign__authorize">
-          {step === 0 &&
+          {!this.state.accountCreationFee && <center><Loading /></center>}
```
Comment (Sekhmet) [inline src/components/Accounts/CreateAccount.js]: nit: We are already destructuring `this.state` so we could destructure `accountCreationFee` as well instead of repeating it.

Comment (Sekhmet) [reply src/components/Accounts/CreateAccount.js]: not nit: By default `accountCreationFee` is set to `0.000 STEEM` which is not falsy value, so all of those checks against `accountCreationFee` are always true (`this.state.accountCreationFee`) or always false (`!this.state.accountCreationFee`). I think we should set default value of `accountCreationFee` to `null`.
