### PR TITLE
Login challenge: add every key_auth codes

### LINKED ISSUE #312: Login challenge fail for user who are not using primary key_auth

### PR DESCRIPTION
**Pull request by bonustrack**
Return array of codes instead of single primary key_auth code for login challenge.

Close #312

### CODE REVIEW

File: routes/api.js [hunk 1]
```diff
@@ -144,7 +144,7 @@ router.post('/broadcast', authenticate('app'), verifyPermissions, async (req, re
 
 router.all('/login/challenge', async (req, res) => {
   const username = req.query.username;
-  const role = req.query.role || 'posting';
+  const role = ['posting', 'active', 'owner'].includes(req.query.role) ? req.query.role : 'posting';
```
Comment (Sekhmet) [inline routes/api.js]: I'm not sure if we have polyfills (I see that we have `babel-polyfill` as dependency but it doesn't seem to be included), but if not this will break in IE11 if we support this browser.

File: src/utils/auth.js [hunk 2]
```diff
@@ -7,9 +7,20 @@ export const login = ({ username, wif, role = 'posting' }, cb) => {
...
     .then((data) => {
-      const token = decode(wif, data.code).substring(1);
-      localStorage.setItem('token', token);
-      cb(null, data);
+      let token;
+      data.codes.forEach((code) => {
+        try {
+          token = decode(wif, code).substring(1);
+        } catch (err) {
+          // console.log(err);
```
Comment (Sekhmet) [inline src/utils/auth.js]: If it fails we can just reject early inside of catch:
```js
cb('Login challenge failed', null);
```

File: routes/api.js (hunk 1 above)
Comment (bonustrack) [reply routes/api.js]: This is on server side
