### PR TITLE
Fix sign operation convert

### LINKED ISSUE #316: /sign/convert operation fails with requestid not integer
Example link: 
https://v2.steemconnect.com/sign/convert?requestid=1&owner=eonwarped&amount=5.000%20SBD 

Full stack trace below:

> Error: transaction.operations = convert,[object Object]	 cause: convert.requestid = 1	 cause: Illegal value: 1 (not an integer) 
 stack: TypeError: Illegal value: 1 (not an integer)
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)  
 stack: Error: convert.requestid = 1	 cause: Illegal value: 1 (not an integer) 
 stack: TypeError: Illegal value: 1 (not an integer)
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021) 
    at Function.value (https://v2.steemconnect.com/js/app.min.js:81:28944)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264446)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)
    at o._resolveCallback (https://v2.steemconnect.com/js/app.min.js:53:44892) 
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)  
 stack: Error: convert.requestid = 1	 cause: Illegal value: 1 (not an integer) 
 stack: TypeError: Illegal value: 1 (not an integer)
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021) 
    at Function.value (https://v2.steemconnect.com/js/app.min.js:81:28944)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264446)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)
    at o._resolveCallback (https://v2.steemconnect.com/js/app.min.js:53:44892) 
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)  
    at o.a.writeUint32 (https://v2.steemconnect.com/js/app.min.js:29:10350)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:269934)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021) 
    at Function.value (https://v2.steemconnect.com/js/app.min.js:81:28944)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264446)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:280436)
    at Object.appendByteBuffer (https://v2.steemconnect.com/js/app.min.js:67:274011)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264328)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)
    at o._resolveCallback (https://v2.steemconnect.com/js/app.min.js:53:44892) 
    at Function.value (https://v2.steemconnect.com/js/app.min.js:81:28944)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:264446)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:265979)
    at e.value (https://v2.steemconnect.com/js/app.min.js:67:266074)
    at Object.h.signTransaction (https://v2.steemconnect.com/js/app.min.js:67:324643)
    at https://v2.steemconnect.com/js/app.min.js:81:208087
    at o (https://v2.steemconnect.com/js/app.min.js:53:72749)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46152)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
    at o._settlePromises (https://v2.steemconnect.com/js/app.min.js:53:48978)
    at o._fulfill (https://v2.steemconnect.com/js/app.min.js:53:48021)
    at o._resolveCallback (https://v2.steemconnect.com/js/app.min.js:53:44892)
    at o._settlePromiseFromHandler (https://v2.steemconnect.com/js/app.min.js:53:46306)
    at o._settlePromise (https://v2.steemconnect.com/js/app.min.js:53:46952)
    at o._settlePromise0 (https://v2.steemconnect.com/js/app.min.js:53:47651)
From previous event:
    at o.h [as _captureStackTrace] (https://v2.steemconnect.com/js/app.min.js:53:10223)
    at o._then (https://v2.steemconnect.com/js/app.min.js:53:41599)
    at o.then (https://v2.steemconnect.com/js/app.min.js:53:39955)
    at Object.x.send (https://v2.steemconnect.com/js/app.min.js:81:207958)
    at Object.x.(anonymous function) [as convertWith] (https://v2.steemconnect.com/js/app.min.js:81:209033)
    at t.<anonymous> (https://v2.steemconnect.com/js/app.min.js:81:319003)
    at n (https://v2.steemconnect.com/js/app.min.js:76:421756)
    at Generator._invoke (https://v2.steemconnect.com/js/app.min.js:76:422801)
    at Generator.e.(anonymous function) [as next] (https://v2.steemconnect.com/js/app.min.js:76:421935)
    at n (https://v2.steemconnect.com/js/app.min.js:12:1263)
    at https://v2.steemconnect.com/js/app.min.js:12:1359

### PR DESCRIPTION
**Pull request by bonustrack**
https://steemd.com/tx/b22ef2ba14dfb699b509cffc6a29277f6d0c2a5d

Closes #316

### CODE REVIEW

File: helpers/operations/convert.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+const cloneDeep = require('lodash/cloneDeep');
+const { isEmpty, userExists, normalizeUsername } = require('../validation-utils');
+
+const parse = (query) => {
+  const cQuery = cloneDeep(query);
+  cQuery.owner = normalizeUsername(cQuery.owner);
+  cQuery.requestid = parseInt(cQuery.requestid, 0);
```
Comment (Sekhmet) [inline helpers/operations/convert.js]: I think that would be better to use `radix` of `10` if `requestId` is always a decimal. eslint complains about not using explicit radix, but passing `0` makes it behave the same way as when radix is omitted.
