### PR TITLE
Fix change recovery account

### LINKED ISSUE #314: Unable to change recovery address
https://v2.steemconnect.com/sign/change_recovery_account?account_to_recover=account1&new_recovery_account=account2&extensions=true

I am getting error.

### LINKED ISSUE #317: Change recovery account operation fail
The operation fail with this error:
image

Here is the link to reproduce the operation:
https://steemconnect.com/sign/change_recovery_account?account_to_recover=hellosteem&new_recovery_account=siol&extensions=[]

### PR DESCRIPTION
**Pull request by bonustrack**
https://steemd.com/tx/0dcbfb46c41efb04130e6dbd5205a552911a1202

Closes #317 
Closes #314

### CODE REVIEW

File: helpers/operations/change-recovery-account.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
+const cloneDeep = require('lodash/cloneDeep');
+const { isEmpty, userExists, normalizeUsername } = require('../validation-utils');
+
+const parse = (query) => {
+  const cQuery = cloneDeep(query);
+  cQuery.account_to_recover = normalizeUsername(cQuery.account_to_recover);
+  cQuery.new_recovery_account = normalizeUsername(cQuery.new_recovery_account);
+  cQuery.extensions = query.extensions ? JSON.parse(query.extensions) : [];
```
Comment (Sekhmet) [inline helpers/operations/change-recovery-account.js]: Can `JSON.parse` fail to parse `query.extensions`?
